addons:
  ssh_known_hosts: gitlab.com
#env:
#  global:
#    - secure: IHP2PqoriP4Rd3+j/G9kSDmcLQ5zAFzCrh+lacfl5eyTEm+dDR9f99bp8kIsyc6i6+qP8ffQKNV3O5CNjJcbfcP/pCWskQPjedSJFqeQRKPb1NzlNknXnjkhC/TrV/boTK0b749bsU87Di31NcIVDKymQMo4FBtm20PQIALJWCiAUvIl3Rpl7sHWMAdnz4EBPSSCr0R3wbOUNMe3jZ0UGm4k4NdONp5jaN4CeGAvtLHD5AG0/6ZjZ2WrmO3vALFzncxtiDHWlX+bwbdGlSNBGdRRrTLjbSp4MYGvz18h5W3wDL/S0fBdnEeNNkyGdc5ATWZc92M3VOV+4UfFTVTixX7trvpulvWx1s1/PXDrSU5vECeAtHS/3MzDPxgzsBk9LgT+sTwqRY2o6a/JLXr5fLFNKWi7ltcNL5O9LkyzqOtzR8XxWEnWGpkcOitqal/lSxhDzi4Lk2Cd/h3OSIyO7TeAGhNd7IeLeND9mhVllyXtkIRXnUIIMBaXZdOIB9i3RrgcnLNlR+yde86PnkHEKoo4Wxny5fP5QUjxT+fD6DCYNdgIWA85NAFEWE+kt0GT5TGQ5sqwFpBS+leZ3r/6Rqn28Rwk/s4WofJJRikzgRP1qtorkLovC8egTYFaAG1tdqG0cSv6rEHGeVOkUi1aVNIorbDpZ/8OOFueXvd8FI8=
jobs:
  include:
  - os: osx
    osx_image: xcode11
    env:
    - TARGET_PLATFORM=ios
    - GPG=gpg
    - FASTLANE_SKIP_UPLOAD=true
  - os: linux
    language: android
    #dist: xenial
    dist: trusty
    android:
      components:
      - tools
      - platform-tools
      - android-27
      - build-tools-28.0.3
      licenses:
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - 'platforms;android-27'
      - 'platforms;android-28'
    before_install:
      - sudo apt-get install -y gnupg2
      - yes | sdkmanager "platforms;android-27"
      - yes | sdkmanager "platforms;android-28"
      - gem update --system
      - gem install fastlane --no-document --quiet
    env:
    - TARGET_PLATFORM=android
    - GPG=gpg2
  - stage: test
    os: linux
    language: android
    dist: trusty
    before_install:
      - sudo apt-get install -y gnupg2
    env:
      - TARGET_PLATFORM=android
    script:
      - fail=false
      - flutter test --coverage || fail=true
      - echo "fail=$fail"
    after_success:
      - source _tools/secrets/secrets.env && export CODECOV_TOKEN && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
before_install:
- which gpg
- which gpg2 || echo "gpg2 not found."
- gpg --version
- echo Test
install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in .travis_sec.tar.enc -out .travis_sec.tar -d
- tar xvf .travis_sec.tar
- "./_tools/ci-install-deps.sh ${TARGET_PLATFORM}"
script:
- cat .travis_sec/blackbox_key | $GPG -v --import
- "./_tools/ci-release.sh ${TARGET_PLATFORM}"
