name: anlage_app_game
description: Anlage.App Market Cap Game

# Version number, the version code will be overwritten during compile time.
version: 1.4.1+42

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  logging: ^0.11.3+2
  shared_preferences: ^0.5.3+4
  dio: ^2.1.13
  path: ^1.6.4
  cached_network_image: ^1.1.1
  intl: ^0.15.8
  url_launcher: ^5.1.2
  package_info: ^0.4.0+6
  device_info: ^0.4.0+2
  rxdart: ^0.22.1+1

  firebase_core: ^0.4.0+8
  firebase_analytics: ^5.0.0
  firebase_performance: ^0.3.0+4
  firebase_messaging: ^5.1.3
  firebase_dynamic_links: ^0.5.0

  provider: ^3.0.0+1
  image_picker: ^0.6.1+3
  share: ^0.6.2+1
  esys_flutter_share: ^1.0.2
  image: ^2.1.4
  timeago: ^2.0.18
  flutter_secure_storage: ^3.2.1+1
  pedantic: ^1.8.0+1

  charts_flutter: ^0.6.0
  lottie_flutter: ^0.2.0

  analytics_event_gen:
    git:
      url: https://github.com/hpoul/analytics_events.git
      ref: master
      path: analytics_event_gen
  flutter_async_utils:
    git:
      url: https://github.com/hpoul/flutter_async_utils.git
      ref: c0205050e93a5a31aa0843a3f25773e09c118261
  built_value: ^6.7.0
  simple_json_persistence: ^0.1.1
  flutter_markdown: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.6
  built_value_generator: ^6.7.0
dependency_overrides:
  pedantic: ^1.8.0+1
  #  analytics_event_gen:
  #    path: ../../analytics_events/analytics_event_gen
#  flutter_async_utils:
#    path: ../flutter_async_utils

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/lottie/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto_Mono/RobotoMono-Regular.ttf
